Check login required in view setup
MTES-MCT/apilos pull request #1087
Opened 2023-12-13 10:47 UTC by etchegom

2023-12-18 12:56 UTC, syldb requested changes
Je verrais bien un test qui vérifie qu'on prend un fail sans login, et que ça passe sinon. Pas forcément évident mais ça ferait pas de mal !

2023-12-18 13:15 UTC, etchegom commented
> Je verrais bien un test qui vérifie qu'on prend un fail sans login, et que ça passe sinon. Pas forcément évident mais ça ferait pas de mal !

On prendra pas un fail sans login, on sera redirigé au moment du dispatch.
Mais je peux tester que si pas de login, `logged_in_setup` ne sera pas appelé.

2023-12-18 14:02 UTC, MarjolaineLB approved these changes
<img src="https://media3.giphy.com/media/MIjrTt2chAJzF2fzL5/giphy.gif"/>

2023-12-18 14:03 UTC, MarjolaineLB commented
il y a un petit rebase à faire ici :)

2023-12-19 08:04 UTC, syldb commented on conventions/tests/views/test_edd_view.py
> +    def test_view_not_logged_get_convention_not_called(self):
J'avais écrit un test générique et défini le chemin vers _get_convention pour chaque sous-classe de test mais... c'est un peu overkill, tester dans une seul sous classe de ConventionView me semble suffisant

2023-12-19 15:15 UTC, etchegom commented on conventions/tests/views/test_edd_view.py
> +            self.assertFalse(mocked_get_convention.called)
Non bloquant: je trouve le commentaire peu utile ici, pourquoi ne pas le déplacer dans le message de l'exception? il aiderait alors à identifier le problème sur un test qui échoue
```python
self.assertFalse(
    mocked_get_convention.called,
    msg="_get_convention should not be called when not authenticated",
)
```

2023-12-22 07:30 UTC, kolok commented on conventions/tests/views/test_edd_view.py
> +            self.assertFalse(mocked_get_convention.called)
👍

2023-12-22 07:36 UTC, kolok commented on conventions/tests/views/test_edd_view.py
> +    def test_view_not_logged_get_convention_not_called(self):
Aprsè le rebase, j'ai peut-être perdu ce test: j'en suis confu, je me demande encore comment c'est possible

2024-01-02 08:54 UTC, closed without merging