Batch designation command
MTES-MCT/apilos pull request #1430
Opened 2024-05-16 14:47 UTC by syldb

Commande temporaire, sera remove après être passée en staging et prod. Le code est tout à la fin du fichier.

Exécution locale:
```
===== EXECUTION SUMMARY ====== 
Conventions updated: 638
Conventions not found: 0
```

Exemple de convention sur laquelle le script a tourné:

![Capture d’écran 2024-05-16 à 16 46 05](https://github.com/MTES-MCT/apilos/assets/26469767/e2824cd3-a7b8-49d6-b031-9aeb3e8920c8)

2024-05-17 07:58 UTC, etchegom commented on conventions/management/commands/denonciation_batch.py
> +            self.sdtout.warn(f"Convention {numero} not found.")
```suggestion
            self.stdout.write(self.style.WARNING(f"Convention {numero} not found."))
```

2024-05-17 07:59 UTC, etchegom requested changes
Attention, typo (sdtout)

2024-05-21 06:16 UTC, syldb commented on conventions/management/commands/denonciation_batch.py
> +            self.sdtout.warn(f"Convention {numero} not found.")
C'est fix, merci 👌

2024-05-21 06:16 UTC, syldb commented on conventions/management/commands/denonciation_batch.py
> +            )
C'est fix, merci 👌

2024-05-21 21:20 UTC, kolok commented on conventions/management/commands/denonciation_batch.py
> +        qs.update(statut=ConventionStatut.DENONCEE.label, date_denonciation=date_python)
Tu n'as aucun avenant sur les conventions dénoncées ? si tu as des avenants, est-ce que ces avenants passent en statut dénoncés aussi ?

Est-ce qu'on n'a pas intérêt à utiliser la fonction `convention_denonciation_validate` pour dénoncer les conventions ?

2024-05-22 08:29 UTC, syldb commented on conventions/management/commands/denonciation_batch.py
> +        qs.update(statut=ConventionStatut.DENONCEE.label, date_denonciation=date_python)
Mmm là j'étais parti pour changer directement sur les conventions, `convention_denonciation_validate` implique de créer un avenant de dénonciation, ce n'est pas ce que j'avais compris du ticket (Ibthiel parlait d'aller changer le statut), mais en effet ça permettrait de le faire sur les avenants et pas uniquement sur les conventions. Je regarde !

2024-05-22 09:18 UTC, syldb commented on conventions/management/commands/denonciation_batch.py
> +        qs.update(statut=ConventionStatut.DENONCEE.label, date_denonciation=date_python)
J'ai le code en local, mais on n'a pas le pdf de l'avenant alors je crée un avenant sans fichier joint, je ne sais pas si c'est ce qu'on veut

2024-05-22 09:19 UTC, syldb commented on conventions/management/commands/denonciation_batch.py
> +        qs.update(statut=ConventionStatut.DENONCEE.label, date_denonciation=date_python)
je peux aussi dénoncer la convention et tous ses avenants en m'inspirant de `convention_denonciation_validate` mais sans l'utiliser

2024-05-22 11:58 UTC, syldb commented on conventions/management/commands/denonciation_batch.py
> +        qs.update(statut=ConventionStatut.DENONCEE.label, date_denonciation=date_python)
Au passage j'ai vérifié, 17 conventions ont des avenants

2024-06-26 06:23 UTC, kolok approved these changes

2024-06-27 07:49 UTC, merged