Branch s402 visibility faq
MTES-MCT/apilos pull request #176
Opened 2022-05-02 19:13 UTC by MarjolaineLB

2022-05-03 05:42 UTC, kolok requested changes

2022-05-03 05:42 UTC, kolok commented on programmes/forms.py
> +        label="Effet relatif",
J'ai un doute sur cette modification car nous avons besoin aussi de pouvoir téléverser des références cadastrales... de plus les effet relatifs ne sont pas encore intégrés au doc de convention.

A voir avec Sabine

2022-05-03 05:42 UTC, kolok commented on static/css/main.css
> +.bordered {
Est-ce qu'on ne devrait pas préfixer nos class avec `apilos-` ?
Et appliquer le principe BAM ?

2022-05-03 05:42 UTC, kolok commented on static/css/main.css
> +.fr-header .fr-links-group > li {
les classes qui commencent par `fr-` sont celles du dsfr. mieux vaux en créer des nouvelles pour ajouter des propriétés.

@MarjolaineLB : qu'en pense-tu ?

2022-05-03 05:42 UTC, kolok commented on templates/common/form/input_textarea.html
> -            {% include "common/help_field.html" with form_input=form_input %}
```
            {% if helptext_visible %}
                {% include "common/help_field.html" with form_input=form_input helptext_visible=True %}
            {% else %}
                {% include "common/help_field.html" with form_input=form_input %}
            {% endif %}
```

idem que 

```
{% include "common/help_field.html" with form_input=form_input %}
```

2022-05-03 05:42 UTC, kolok commented on templates/common/form/input_upload.html
> +                {% if additional_informations_tooltip %}
additional_informations_tooltip est utilisée une seule fois, on peut peut-être modifier le comportement pour s'en passer ?

2022-05-03 05:42 UTC, kolok commented on templates/common/help_field.html
> +    {% if helptext_visible %}
yeah!!!

Cool de supprimer du code JS

Est-ce possible de faire en sorte que l'icone 'i' ne passe pas à la ligne quand on clique dessus ?

<img width="170" alt="Screenshot 2022-05-03 at 07 37 58" src="https://user-images.githubusercontent.com/454431/166408774-194a6441-f250-4811-992c-fb64a08c4255.png">

<img width="447" alt="Screenshot 2022-05-03 at 07 38 08" src="https://user-images.githubusercontent.com/454431/166408788-8c6bdc66-8c45-4ebf-a623-f2bfb9b2af02.png">

2022-05-03 06:24 UTC, MarjolaineLB commented on programmes/forms.py
> +        label="Effet relatif",
Les références cadastrales sont présentes sur la page un peu au dessus (cf ligne 68)

2022-05-03 06:26 UTC, MarjolaineLB commented on static/css/main.css
> +.bordered {
On peut, il m'a semblé que ce n'était pas le cas jusque là mais on peut commencer à le faire. Pour le principe, tu parles du principe BEM ?

2022-05-03 06:26 UTC, MarjolaineLB commented on static/css/main.css
> +.fr-header .fr-links-group > li {
ça me va :)

2022-05-03 06:27 UTC, MarjolaineLB commented on templates/common/form/input_textarea.html
> -            {% include "common/help_field.html" with form_input=form_input %}
mhmmm dans un cas on a helptext_visible=True et pas dans l'autre

2022-05-03 06:27 UTC, MarjolaineLB commented on templates/common/form/input_upload.html
> +                {% if additional_informations_tooltip %}
j'ai hésité :)

2022-05-03 06:28 UTC, MarjolaineLB commented on templates/common/help_field.html
> +    {% if helptext_visible %}
on en parle, je te montre ce qu'il est possible de faire. :)

2022-05-04 15:26 UTC, MarjolaineLB commented
j'ai poussé  des nouvelles modifs suite à ta review. Tu jettes un oeil à nouveau ?

2022-05-06 09:34 UTC, kolok approved these changes
APPROVED !!!

ho yeah !

2022-05-06 09:40 UTC, merged