S392 prefix free
MTES-MCT/apilos pull request #189
Opened 2022-05-20 09:50 UTC by MarjolaineLB

2022-05-22 21:24 UTC, kolok requested changes

2022-05-22 21:24 UTC, kolok commented on conventions/forms.py
> +                f"Le numéro de convention que vous avez indiqué est identique au préfixe défini pour votre administration."
l'erreur peut-être plus explicite pour l'instructeur

2022-05-22 21:24 UTC, kolok commented on conventions/services/services_conventions.py
> +                "convention_numero": convention.get_convention_prefix() if convention.programme.administration else ""
le test peut-être fait dans la fonction get_convention_prefix

2022-05-22 21:24 UTC, kolok commented on conventions/models.py
> +                return self.programme.administration.prefix_convention.replace("{département}", str(self.programme.code_postal[:-3])).replace("{zone}", str(self.programme.zone_123_bis)).replace("{moi
quelques retours à la ligne seraient les bienvenus

même problème que les hooks de precommit

2022-05-22 21:24 UTC, kolok commented on .pre-commit-config.yaml
> +      language_version: python3.10
pas en rapport avec la fonctionnalité...
à livrer à part...

2022-05-22 21:24 UTC, kolok commented on conventions/forms.py
> +    uuid = forms.UUIDField(
On pourrait essayer d'assigner la convention directement ici au liu de la récupérer à partir de la base de données

2022-05-22 21:24 UTC, kolok commented on instructeurs/forms.py
> +            "max_length": "Le préfixe du numérp de convention ne doit pas excéder 255 caractères",
typo : numérp

2022-05-22 21:24 UTC, kolok commented on instructeurs/forms.py
> +        test=re.findall(r"\{\w+\}", prefix_convention)
la variable test peut-être renommée pour que le code soit plus explicite

2022-05-22 21:24 UTC, kolok commented on conventions/services/services_conventions.py
> +                "convention_numero": convention.get_convention_prefix() if convention.programme.administration else ""
doit-être initié avec le numéro de convention si celui-ci n'est pas null,
sinon le prefix

2022-05-23 14:42 UTC, MarjolaineLB commented on conventions/services/services_conventions.py
> +                "convention_numero": convention.get_convention_prefix() if convention.programme.administration else ""
> le test peut-être fait dans la fonction get_convention_prefix

dans la fonction, je fais le test : `if self.programme.administration:` est-ce que ça ne suffit pas du coup ? Est-ce que je dois prévoir un `else` ?

2022-05-23 14:42 UTC, MarjolaineLB commented on conventions/services/services_conventions.py
> +                "convention_numero": convention.get_convention_prefix() if convention.programme.administration else ""
> doit-être initié avec le numéro de convention si celui-ci n'est pas null, sinon le prefix

pas sûre de comprendre. Le numéro de convention peut ne pas être nul à ce stade ?

2022-05-23 14:47 UTC, MarjolaineLB commented on conventions/forms.py
> +                f"Le numéro de convention que vous avez indiqué est identique au préfixe défini pour votre administration."
> Le numéro de convention ne doit pas être identique au préfixe défini pour votre administration. Vous devez ajouter un numéro spécifique à la convention.

Est-ce que ça te paraît suffisamment explicite ?

2022-05-24 08:35 UTC, MarjolaineLB commented on conventions/forms.py
> +                f"Le numéro de convention que vous avez indiqué est identique au préfixe défini pour votre administration."
Attention, le champ est  uniquement prérempli avec le préfixe du numéro de convention déterminé pour votre administration. Il semble que vous n'avez pas ajouté à la suite de ce préfixe de numéro spécifique pour votre convention.

2022-05-24 08:54 UTC, kolok reviewed
OK

2022-05-24 08:55 UTC, kolok approved these changes
Vu avec Marjolaine

2022-05-24 16:07 UTC, MarjolaineLB commented on .pre-commit-config.yaml
> +      language_version: python3.10
je sais que c'est pas en rapport avec la fonctionnalité mais si je le vire mon pre-commit plante. On peut le laisser ?

2022-05-24 20:04 UTC, merged