s543 Add route to create conventions
MTES-MCT/apilos pull request #357
Opened 2022-10-24 06:05 UTC by kolok

links to [s543](https://airtable.com/appqEzValO6eQoHbM/tblNIOUJttSKoH866/viwDAEFTTtrDtmrWs/recN44SL7qTuVvjAV?blocks=hide)

Callable route to create operation while SIAP operation is ready to be "conventionned"

2022-10-24 13:28 UTC, pierrelemee requested changes
Ça m'a l'air de faire le taf, mais je pense qu'il serait plus prudent de couvrir avec des tests unitaires 👼

2022-10-24 13:42 UTC, kolok commented on programmes/api/operation_api_views.py
> +    def post(self, request, numero_galion):
👍

2022-10-27 10:15 UTC, pierrelemee approved these changes
![failure proof](https://media.giphy.com/media/Gzl3orJCiEc76HBXa6/giphy.gif)

Bien joué pour les tests 👍

2022-10-27 10:15 UTC, pierrelemee commented on programmes/api/tests/test_apis.py
> +        settings.USE_MOCKED_SIAP_CLIENT = True
Ok j'ai parcouru un peu le code et j'ai compris que ça servait pour la _dependency inversion_, bien joué 👏

2022-10-31 08:22 UTC, merged