S659 avenants conventions hors apilos
MTES-MCT/apilos pull request #423
Opened 2022-11-29 17:50 UTC by MarjolaineLB

2022-12-12 10:22 UTC, pierrelemee requested changes
J'ai juste un petit doute sur la recherche de convention d'avenant qui risque d'être très peu performante sans paramètres par défaut :|

2022-12-12 10:22 UTC, pierrelemee commented on conventions/services/services_programmes.py
> +                statut=(
💡 tu as aussi la possibilité de définir ces valeurs dans la méthode `clean` de l'objet `Form`

2022-12-12 10:22 UTC, pierrelemee commented on conventions/services/services_programmes.py
> +                self.convention.save()
Ce bout de code va maintenant être dupliqué 3 fois avec [ce que j'ai fait sur les pièces jointes d'Ecoloweb](https://github.com/MTES-MCT/apilos/pull/437/files#diff-fa60c4b6d003e102d5a8d3b79906baa55473e5462dae1b4cb58cb17abd9a6f9fR396) => ça mériterait d'être délégué à un service dans `conventions` je pense

2022-12-12 10:22 UTC, pierrelemee commented on conventions/services/services_conventions.py
> +    departement = request.GET["departement"]
Entre le volume de données que je vais ramener depuis Ecoloweb, le fait que cette recherche sera faite sans paramètre la première fois et [la règle de "never trust user input"](https://laravel-news.com/never-trust-your-users) j'aurais envie de conseiller de:
* soit ne pas jouer la requête si le moindre paramètre est manquant
* soit rajouter un `limit` (via `[:10]` ou quelque chose comme ça)

2022-12-12 10:25 UTC, MarjolaineLB commented
> J'ai juste un petit doute sur la recherche de convention d'avenant qui risque d'être très peu performante sans paramètres par défaut :|

Pas sûre de savoir comment gérer des paramètres par défaut, à part peut être sur l'année courante mais pour le reste, ce sont des critères qui sont vraiment propres à chacun. Par contre, les 3 critères sont obligatoires pour lancer la recherche

2022-12-12 10:26 UTC, MarjolaineLB commented on conventions/services/services_conventions.py
> +    departement = request.GET["departement"]
les paramètres sont obligatoires dans le formulaire

2022-12-12 10:27 UTC, MarjolaineLB commented on conventions/services/services_programmes.py
> +                statut=(
pas sûre de comprendre comment puisque la valeur dépend de la présence ou non de l'input dans le formulaire

2022-12-12 16:00 UTC, pierrelemee commented on conventions/services/services_programmes.py
> +                self.convention.save()
J'ai créé le ticket ✅

2022-12-12 16:40 UTC, pierrelemee approved these changes
![avenant](https://media.giphy.com/media/a9dGnkMNSSwDeR8Xii/giphy.gif)

2022-12-21 10:26 UTC, pierrelemee approved these changes
![modifier](https://media.giphy.com/media/l0HlD16JLCQzBU4jC/giphy.gif)

2022-12-26 17:09 UTC, merged