Création d'avenant sur des convention créée hors APiLos - validation de l'avenant
MTES-MCT/apilos pull request #557
Opened 2023-02-16 15:28 UTC by MarjolaineLB

Dans le cadre de création d'avenants sur des conventions non présentes dans APiLos, il est demandé au bailleur de remplir certaines informations sur la convention au démarrage.

A l'étape  de validation de l'avenant, il est demandé à l'instructeur de compléter avec les informations manquantes sur la convention avant de pouvoir valider l'avenant.
Ces informations sont : 
- villes
- nombre de logements
- pdf de la convention originale si cela manque.

2023-03-10 10:48 UTC, pierrelemee requested changes
Des petites remarques de formes comme de fond pour ma part. Plus largement je suis assez confus sur ce que tu essayes de faire ici: le but est de modifier les infos `ville`, `nb_logements`, `nom_fichier_signe` sur la convention _racine_ avant la création d'avenant ? Ou justement sur un avenant ? Quels sont les critères d'éligibilité ?

2023-03-10 10:48 UTC, pierrelemee commented on conventions/services/recapitulatif.py
> +            "ville": convention.parent.programme.ville,
Attention parce que la convention n'est pas forcément un avenant, et par conséquent n'a potentiellement pas de de `parent` ...

2023-03-10 10:48 UTC, pierrelemee commented on conventions/forms/avenant.py
> +    Formulaire qui permet à l'instructeur de compléter les informations de la convention
On est d'accord que ce formulaire ne se destine qu'à des conventions qui auraient été "importées" ? Donc ni créée sur Apilos ni migrée d'Ecoloweb, c'est bien ça ?

2023-03-10 10:48 UTC, pierrelemee commented on conventions/forms/avenant.py
> +    Formulaire qui permet à l'instructeur de compléter les informations de la convention
Par extension ça vaudrait le coup que tu rajoutes `self.convention` au constructeur comme attribut de classe, soit la convention sur laquelle opérer ces changements 💡

2023-03-10 10:48 UTC, pierrelemee commented on conventions/services/recapitulatif.py
> +            parentconvention = convention.parent
En théorie tu n'as pas vraiment besoin de toutes ces variables locales, car si la `convention` est bien hydraté (à coup de `prefetch_related`, tu peux accéder directement aux objets liés:

```py
convention.parent.programme.ville = form.cleaned_data["ville"]
```

Etc...

2023-03-10 10:48 UTC, pierrelemee commented on templates/conventions/actions/instructeur_validation.html
> +                {% include "conventions/avenant/complete_form_for_avenants.html" %}
Dans une logique de réusabilité / atomicité tu pourrais déclarer le formulaire comme étant variable `form` dans le sous template:

```
with form=complete_for_avenant_form
```

2023-03-10 10:48 UTC, pierrelemee commented on templates/conventions/actions/instructeur_validation.html
> +                {% include "conventions/avenant/complete_form_for_avenants.html" %}
En plus ledit `form` peut être `None` (cf. mon commentaire sur la view ☝️  qui ne vérifie pas que la convention est un avenant) puisqu'ici tu testes juste avant que la convention est bien un avenant :)

2023-03-17 06:11 UTC, kolok reviewed
juste un doute sur le comportement du formulaire si il n'est pas valide !

2023-03-17 06:11 UTC, kolok commented on conventions/views/conventions.py
> +    else:
Pourquoi on ne peut pas utiliser `result["success"]`

Est-ce que tu as testé si le formulaire avait une erreur, ex : un nom de ville trop longue ?

2023-03-17 09:45 UTC, MarjolaineLB commented on conventions/views/conventions.py
> +    else:
mhmmm bonne remarque

2023-03-17 13:25 UTC, merged