enhance performance when creating conventon from list of lot
MTES-MCT/apilos pull request #559
Opened 2023-02-19 20:04 UTC by kolok

* get list of lot using sql to count nb_convention by lot
* remove the call to conventions for each lot

2023-02-20 08:46 UTC, pierrelemee requested changes
Je me suis permis de faire un petit comparatif avec ce script:

```py
import time

from django.db.models import Count

from users.models import User

user = User.objects.get(username='pierre.lemee')

# Old method
start = time.time()
lots = (
    user.lots()
    .prefetch_related("programme")
    .prefetch_related("conventions")
    .order_by(
        "programme__ville", "programme__nom", "nb_logements", "financement"
    )
    .filter(programme__parent_id__isnull=True, conventions__isnull=True)
)

count = len(lots)
stop = time.time()
print(f"Old method:  🕘 {(stop - start)} 📊 {count}")

# New method
start = time.time()
lots = (
    user.lots()
    .select_related("programme")
    .annotate(nb_conventions=Count("conventions"))
    .order_by(
        "programme__ville", "programme__nom", "nb_logements", "financement"
    )
    .filter(programme__parent_id__isnull=True, nb_conventions=0)
)
count = len(lots)
stop = time.time()
print(f"New method:  🕘 {(stop - start)} 📊 {count}")
```

Et malheureusement voici les résultats (en staging):

```
Old method:  🕘 8.676697254180908 📊 62173
New method:  🕘 68.35283732414246 📊 62173
```

Certes le `select_related` nous épargne le N+1 mais 68s c'est beaucoup trop. Après je peux faire le test sur un utilisateur avec moins de résultat si tel était ton idée ...

2023-02-20 21:40 UTC, kolok commented
Incroyable !

Je n'ai pas du tout les mêmes chiffres en local et en staging.

En local

```
>>> old_method(user)
Old method:  🕘 11.377496719360352 📊 78762
>>> new_method(user)
New method:  🕘 10.062994956970215 📊 78762
>>> new_method(user)
New method:  🕘 9.14746356010437 📊 78762
>>> old_method(user)
Old method:  🕘 11.1526939868927 📊 78762
```

en staging:

```
>>> new_method(user)
New method:  🕘 4.695112466812134 📊 62171
>>> old_method(user)
Old method:  �� 8.298451662063599 📊 62171
>>> old_method(user)
Old method:  �� 21.263748168945312 📊 62171
>>> new_method(user)
New method:  🕘 54.1208176612854 📊 62171
>>> old_method(user)
Old method:  �� 16.99536108970642 📊 62171
>>> new_method(user)
New method:  🕘 77.0290515422821 📊 62171
```

Puis dans un deuxième essai:

```
>>> old_method(user)
Old method:  �� 10.016208171844482 📊 62171
>>> new_method(user)
New method:  🕘 94.71927309036255 📊 62171
```

compliqué à expliquer.

Merci d'avoir tester, je vais rollback la partie requête dans un premier temps

2023-02-20 22:31 UTC, kolok commented
En faite, c'est un peu eratique :
```
>>> new_method(user)
New method:  🕘 4.2714197635650635 📊 62171
>>> new_method(user)
New method:  🕘 4.012037992477417 📊 62171
>>> new_method(user)
New method:  🕘 3.9387152194976807 📊 62171
>>> new_method(user)
New method:  🕘 4.084091424942017 📊 62171
>>> new_method(user)
New method:  🕘 4.174100875854492 📊 62171
>>> old_method(user)
Old method:  �� 9.556735277175903 📊 62171
>>> old_method(user)
Old method:  �� 102.6335461139679 📊 62171
>>> old_method(user)
Old method:  �� 32.619738817214966 📊 62171
>>> new_method(user)
New method:  🕘 83.7285623550415 📊 62171
>>> new_method(user)
New method:  🕘 4.069138050079346 📊 62171
>>> new_method(user)
New method:  🕘 4.109944105148315 📊 62171
>>> new_method(user)
New method:  🕘 4.094828128814697 📊 62171
>>> new_method(user)
New method:  🕘 3.9412522315979004 📊 62171
>>> new_method(user)
New method:  🕘 3.9304988384246826 📊 62171
>>> new_method(user)
New method:  🕘 3.8869333267211914 📊 62171
>>> new_method(user)
New method:  🕘 4.119102716445923 📊 62171
>>> old_method(user)
Old method:  �� 8.719046592712402 📊 62171
>>> new_method(user)
New method:  🕘 13.684674739837646 📊 62171
>>> new_method(user)
New method:  🕘 4.094380855560303 📊 62171
>>> new_method(user)
New method:  🕘 3.963794708251953 📊 62171
>>> old_method(user)
Old method:  �� 8.811172723770142 📊 62171
>>> old_method(user)
Old method:  �� 77.86523270606995 📊 62171
>>> old_method(user)
Old method:  �� 28.05724859237671 📊 62171
>>> new_method(user)
New method:  🕘 53.08315706253052 📊 62171
>>> new_method(user)
New method:  🕘 4.020422697067261 📊 62171
>>> new_method(user)
New method:  🕘 4.027888774871826 📊 62171
>>> new_method(user)
New method:  🕘 4.3014607429504395 📊 62171
```

2023-02-21 14:11 UTC, pierrelemee approved these changes
![enhance](https://media.giphy.com/media/Wiepe7LEg3MWc/giphy.gif)

2023-02-21 14:43 UTC, merged