S871: Appel SIAP, retry x2, timeout 3s
MTES-MCT/apilos pull request #741
Opened 2023-04-25 17:40 UTC by pierrelemee

# S871: Appel SIAP, retry x2, timeout 3s

Parce qu'[on reçoit des `TimeoutException`](https://sentry.incubateur.net/organizations/betagouv/issues/15909/) de temps en temps en appelant le SIAP, on opte de [descendre le `timeout` d'un appel à 3s et de ré-essayer (`retry`) 2 fois][https://airtable.com/appqEzValO6eQoHbM/tblNIOUJttSKoH866/viwDAEFTTtrDtmrWs/reckzyl7KH8S8b6d0?blocks=hide) (donc 3 tentatives au total)

Vous noterez au passage que le linting ça me saoule religieusement

2023-04-26 07:52 UTC, kolok reviewed
il exist un package qui fait ça pout toi:

https://tenacity.readthedocs.io/en/latest/

déjà testé sur SPPNaut, c'est hyper simple et ça marche nickel avec sentry

2023-04-26 09:55 UTC, pierrelemee commented
> il exist un package qui fait ça pout toi:
> 
> https://tenacity.readthedocs.io/en/latest/
> 
> déjà testé sur SPPNaut, c'est hyper simple et ça marche nickel avec sentry

Ok j'ai mis à jour sur le dernier commit

2023-04-26 15:16 UTC, kolok requested changes

2023-04-26 15:16 UTC, kolok commented on siap/siap_client/client.py
> +        except PylintException:
ici ça ne va pas marcher car il ne passera l'exception que pour une exception de type PylintException, c'est à dire jamais.

`except Exception` doit fonctionner dans ptous les cas

2023-04-26 15:16 UTC, kolok commented on siap/siap_client/client.py
>  def _call_siap_api(
On ne veut retenter qu'une seul fois

et tu peux mettre le retry directement sur la fonction _call_siap_api :

```
@retry(@retry(retry=retry_if_exception_type(TimeoutSIAPError), stop=stop_after_attempt(2))
```

2023-04-26 15:16 UTC, kolok commented on siap/siap_client/client.py
> +def _siap_get(url, params=None, timeout=3, **kwargs) -> Response:
pas besoin de cette fonction, cf. le commentaire ci-dessous

2023-04-26 15:16 UTC, kolok commented on siap/siap_client/client.py
> +class PylintException(Exception):
pas besoin de cette Exception, cf. le commentaire ci-dessous

2023-05-03 07:22 UTC, pierrelemee commented on siap/siap_client/client.py
> +        except PylintException:
Le problème vient de `pylint` qui ne tolère pas le `except` sur la classe racine ...

2023-05-03 11:54 UTC, MarjolaineLB approved these changes

2023-05-03 12:13 UTC, merged