S900 Adapter la recherche de conventions par onglet
MTES-MCT/apilos pull request #803
Opened 2023-05-31 15:43 UTC by pierrelemee

# S900 Adapter la recherche de conventions par onglet

L'objectif ici était de retravailler l'adaptation de la recherche de conventions par onglet. Pour faire ça j'ai retravaillé les routes mais surtout le service `ConventionListService` que j'ai déprécié au profit de sous classes de services `ConventionSearchBaseService`.

J'ai également initié pas mal de changements niveau template pour rendre la compréhension des variables la plus simple possible.

2023-07-05 13:25 UTC, kolok reviewed
J'ai pas tout relu…

2023-07-07 16:06 UTC, fabienheureux commented on conventions/migrations/0068_remove_convention_unique_display_name_and_more.py
> +                    ("A_SIGNER", "4. À signer"),
J'ai juste ajouté un accent sur le `A` ici, pas  d'autre changement

2023-07-21 09:14 UTC, fabienheureux commented on conventions/services/avenants.py
Déplacer `convention_post_action` dans avenants

2023-07-21 09:41 UTC, fabienheureux commented on conventions/tests/views/test_index_view.py
> +        print(str(galion_refs))
```suggestion
```

2023-07-21 09:44 UTC, fabienheureux commented on conventions/views/conventions.py
> +    def post(self, request: AuthenticatedHttpRequest, convention_uuid: int):
```suggestion
    def post(self, request: HttpRequest, convention_uuid: int):
```

2023-07-21 09:52 UTC, fabienheureux commented on conventions/views/conventions.py
> +    statuses: list
vérifier qu'on en a besoin ici, ca devrait plutôt vivre sur le service (c'est déjà défini dessus)

2023-07-21 09:54 UTC, fabienheureux commented on conventions/services/search.py
> +    order_by = "televersement_convention_signee_le"
pas cohérent

2023-07-21 09:54 UTC, fabienheureux commented on conventions/services/search.py
> +    order_by = "televersement_convention_signee_le"
Vérifier avec Sabine

2023-07-21 09:56 UTC, fabienheureux commented on conventions/views/conventions.py
> +        super().setup(*args, **kwargs)
https://docs.djangoproject.com/en/4.2/ref/class-based-views/base/

2023-07-21 10:02 UTC, fabienheureux commented on conventions/views/conventions.py
> +        uuid = self._get_uuid_for("administration")
voir si indispensable...un peu alambiqué

2023-07-21 10:08 UTC, fabienheureux commented on conventions/views/conventions.py
> +    def _user_convention_statuses_choices(self, user: User) -> list[tuple[str, str]]:
vérifier le fonctionnement côté frontend

2023-07-21 10:12 UTC, fabienheureux commented on conventions/services/search.py
> +    verbose_name = "en instruction"
ajouter verbose_name_plural

2023-07-21 10:15 UTC, fabienheureux commented on conventions/views/conventions.py
> +            administration=self.administration,
vérifier où elle est définie

2023-07-21 10:16 UTC, fabienheureux commented on conventions/views/conventions.py
> +    def administration(self) -> Administration | None:
vérifier si utilisé ailleurs, sinon déplacer dans setup

2023-07-21 10:16 UTC, fabienheureux commented on conventions/views/conventions.py
> +    def bailleur(self) -> Bailleur | None:
vérifier si utilisé ailleurs, sinon déplacer dans setup

2023-07-21 10:18 UTC, fabienheureux commented on programmes/views.py
> +            "conventions": service.get_results(),
vérifier fonctionnement côté frontend

2023-07-21 10:28 UTC, fabienheureux commented on templates/conventions/convention_list.html
> +                                            {% if not active or siap_operation and convention.programme.numero_galion %}
@MarjolaineLB vérifier la logique

2023-07-21 10:29 UTC, fabienheureux commented on templates/conventions/home/_tab.html
> +            <span class="fr-link">{{ tab.count }} {{ tab.title }}</span>
gérer le pluriel

2023-07-21 10:30 UTC, fabienheureux commented on templates/conventions/index.html
> +            {% include "conventions/home/bailleur_no_convention.html" %}
vérifier ce changement

2023-07-21 10:31 UTC, fabienheureux commented on users/models.py
> +    def conventions(self, active: bool | None = None, without_avenants: bool = False):
supprimer la modification

2023-07-21 10:31 UTC, fabienheureux commented on users/models.py
> +        if without_avenants:
supprimer la modification

2023-08-02 16:08 UTC, fabienheureux commented on templates/conventions/convention_list.html
> +                                            {% if not active or siap_operation and convention.programme.numero_galion %}
@kolok 😇

2023-08-03 06:41 UTC, kolok requested changes
Nickel !

Juste une fonction me pose question : `get_uuid_or_none`

Il faudra aussi qu'on teste bien cette fonctionnalité en version SIAP !

2023-08-03 09:20 UTC, fabienheureux commented on core/utils.py
> +def get_uuid_or_none(uuid_or_string):
oui ! je supprime, bien vu

2023-08-03 10:03 UTC, fabienheureux commented on templates/conventions/index.html
> +            {% include "conventions/home/bailleur_no_convention.html" %}
@kolok la logique te semble ok ici ?

2023-08-04 09:51 UTC, kolok reviewed
![](https://media.giphy.com/media/aYzxVt2lMrZXW/giphy.gif)

2023-08-04 09:51 UTC, kolok commented on templates/conventions/index.html
> +            {% include "conventions/home/bailleur_no_convention.html" %}
oui

2023-08-04 09:51 UTC, kolok approved these changes

2023-08-04 09:53 UTC, merged