S945 remove siap users standalone
MTES-MCT/apilos pull request #910
Opened 2023-08-08 16:29 UTC by fabienheureux

2023-08-14 06:43 UTC, kolok requested changes

2023-08-14 06:43 UTC, kolok commented on users/migrations/0025_auto_20230807_1716.py
> +    users_to_delete = User.objects.filter(email__in=duplicates).exclude(
C'est l'inverse qu'on souhaite faire : supprimer tous les utilisateur non CERBERE

2023-08-14 06:43 UTC, kolok commented on users/migrations/0025_auto_20230807_1716.py
Je l'aurais plutôt mis dans une command avec une option dry-run qui liste les utilisateurs qui vont être supprimer.

Qu'en penses-tu ?

2023-08-14 09:47 UTC, kolok requested changes

2023-08-14 09:47 UTC, kolok commented on DEVELOPPEUR.md
> +Supprime les utilisateurs disposant d'un compte APiLos standalone et SIAP.
```suggestion
Supprime les comptes des utilisateurs de la plateforme autonome si ils disposent d'un compte APiLos en version SIAP.
```

2023-08-14 09:47 UTC, kolok commented on users/management/commands/remove-duplicate-siap-users.py
> +    users_to_delete = User.objects.filter(email__in=duplicates).exclude(
```suggestion
    users_to_delete = User.objects.filter(email__in=duplicates).filter(
```

2023-08-14 09:47 UTC, kolok commented on users/management/commands/remove-duplicate-siap-users.py
> +    logger.info("%s emails en doublons détectés", len(duplicates))
j'ai l'impression que ce log est appelé 2 fois : dans la command (handle) et dans la fonction

2023-08-14 10:09 UTC, fabienheureux commented on users/management/commands/remove-duplicate-siap-users.py
> +    logger.info("%s emails en doublons détectés", len(duplicates))
bizarre j'avais fait le changement mais j'ai du le commit sur une mauvaise branche...désolé c'est corrigé !

2023-08-14 10:09 UTC, fabienheureux commented on users/management/commands/remove-duplicate-siap-users.py
> +    users_to_delete = User.objects.filter(email__in=duplicates).exclude(
idem

2023-08-29 11:48 UTC, kolok approved these changes
![](https://media.giphy.com/media/l2R06FEpVRk6IroNq/giphy.gif)

2023-08-29 11:49 UTC, merged