S960 bouton retirer de l avenant
MTES-MCT/apilos pull request #993
Opened 2023-10-12 14:57 UTC by MarjolaineLB

To do : 

- [ ] remplir AVENANT_TYPE_FIELDS_MAPPING dans le model avenant_type
- [ ] envoyer le signal `remove` sur l'avenantType
- [ ] corriger les test
- [ ] supprimer le `# pylint: disable=W0613` sur le modèle convention : dans `post_save_reset_avenant_fields_after_block_delete`

2023-10-23 10:06 UTC, niconoe commented on conventions/models/convention.py
> +                else:
Simplifier ? Redondance possible avec l 726 etc dans _update_nested_convention_field() ?

2023-11-27 17:40 UTC, kolok requested changes
Déso marjo : il en manque : par exemple, pour un foyer dans l'étape bailleur il y a les champs liés au gestionnaire :

![CleanShot 2023-11-27 at 18 38 28@2x](https://github.com/MTES-MCT/apilos/assets/454431/b77f6cbb-082e-4d9e-8c56-41fa9698d62f)

2023-12-12 08:47 UTC, etchegom commented on conventions/signals.py
> +            item.clone(instance)
:thinking: @MarjolaineLB je vais avoir besoin d'un éclaircissement sur cette partie

2023-12-12 08:48 UTC, etchegom commented on conventions/signals.py
> +                )[1]
Il faudrait ajouter du test sur cette partie

2023-12-12 08:50 UTC, etchegom commented on conventions/tests/models/test_avenant_type.py
> +                assert f"missing test for field mapping entry: {field_name}"
Le but de ce test est de faire en sorte que si un des champs est supprimé ou renommé, on pense à mettre à jour le mapping (`Programme._meta.get_field(...)` va lever une exception).

2023-12-18 11:05 UTC, MarjolaineLB commented on conventions/signals.py
> +                )[1]
@etchegom je te laisse prendre la main là-dessus, ok ?

2023-12-20 08:06 UTC, etchegom commented on conventions/views/avenants.py
> +    convention = Convention.objects.get(uuid=convention_uuid)
C'est fait [ici](https://github.com/MTES-MCT/apilos/pull/993/files#diff-b09a309e95e2f63a2521dc4fbc57eb2d185daa759f914ae39176c9b1faa06c63R175), on filtre les avenants.

2023-12-20 11:36 UTC, etchegom commented on conventions/services/avenants.py
> +            avenant.save()  # TODO: check if this is necessary
Pas sûr que ce save serve vraiment, mais il n'y a pas de tests sur cette partie pour le moment je crois bien

2023-12-20 11:37 UTC, etchegom commented on conventions/services/avenants.py
> +                    )
Je pense que ça vaut le coup d'englober le clonage dans une transaction, qu'en pensez-vous?

2023-12-20 11:38 UTC, etchegom commented on conventions/services/avenants.py
> +        avenant.avenant_types.remove(avenant_type)
Idem, je préfère ici l'englober dans une transaction, car on va derrière créer d'autres objets, faire des delete, etc...

2023-12-20 11:38 UTC, etchegom commented on conventions/signals.py
> +        )
Jste un garde-fou

2023-12-22 08:42 UTC, etchegom commented on conventions/signals.py
> +                )[1]
Fixed!

2024-01-08 11:11 UTC, kolok reviewed
Ok pour moi !

2024-01-08 11:11 UTC, kolok approved these changes

2024-01-08 12:36 UTC, merged